name: Deploy

on: push

jobs:
  deploy:
    uses: jansen44/demo-argo/.github/workflows/deploy.yaml@main
    with:
      image: toybeaver/demo-1
      app: demo-1
      env: dev
      project: demo
    secrets:
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
      ghPAT: ${{ secrets.GH_TOKEN }}
