name: Publish Docker image

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: toybeaver/demo-1
          tags: |
            type=sha,enable=true,prefix=sha-,format=short
      - name: debug
        run: |
          echo ${{ steps.meta.outputs.tags }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  commit_new_version:
    name: Commit to ArgoCD config repo with new version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "jansen44/demo-argo"
          token: ${{ secrets.GH_TOKEN }}

      - name: debug
        run: |
          ls

# sed -i -e 's/\(image:.*:\).*$/\1new-tag/' deployment.yaml
#
#     sed -i -e 's/\(image:.*:\).*$/\1new-tag/' deployment.yaml
