name: Deploy

on: push

jobs:
  deploy:
    uses: jansen44/demo-argo/.github/workflows/deploy.yml@main
    with:
      image: toybeaver/demo-1
      deploymentFilePath: dev/apps/demo-1/deployment.yaml
    secrets:
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
      ghPAT: ${{ secrets.GH_TOKEN }}
